= Instructions for Pushing Catalog App

== Prepare the POC code

. Unzip the poc code to a working diretory
. Unzip the com..provider zip
. Open build.gradle
. Change springBootVersion
+
----
springBootVersion = "1.3.6.RELEASE" 
----
+
----
classpath 'org.springframework.boot:spring-boot-gradle-plugin:1.3.6.RELEASE'
----
+
. To avoid logging library conflicts, exclude `logback-classic` from the `spring-boot-gradle-plugin`, `spring-boot-starter-web`, `spring-boot-starter-actuator`, and `spring-boot-starter-jersey` dependencies (the last is in the `:provider-core` project), e.g.
+
[source,java]
----
compile ("org.springframework.boot:spring-boot-starter-jersey:${springBootVersion}") {
    exclude module: "logback-classic"
}
----
+
. In the `:provider-catalog` project, uncomment the `apply plugin: 'war'` instruction
. In the `:provider-catalog` project, set the Spring Boot main class:
+
[source,java]
----
	bootRepackage {
		mainClass = "com.mckesson.pt.catalog.ProviderCatalogApplication"
	}
----
+
. In the `:provider-catalog` project, add the following line to indicate that embedded tomcat is not needed.
+
[source,java]
----
providedRuntime("org.springframework.boot:spring-boot-starter-tomcat")
----
+
. In the catalog module, edit `com.mckesson.pt.catalog.ProviderCatalogApplication`
. First, extend `SpringBootServletInitializer`, e.g.:
+
[source,java]
----
public class ProviderCatalogApplication extends SpringBootServletInitializer {
----
+
. And then, override the configure method:
+
[source,java]
----
    @Override
    protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
        return application.sources(ProviderCatalogApplication.class);
    }
----
+
. Add imports as necessary
+
[source,java]
----
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.context.web.SpringBootServletInitializer;
----
